name: abc file changes

on:
  push:
    branches:
      - main
    paths:
      - 'abc/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and deployment steps specific to changes in the abc folder here
      - name: Example Step
        run: echo "Performing actions for changes in abc folder"
