name: Folder-specific Workflows

on:
  push:
    branches:
      - main

jobs:
  folder_actions:
    name: Folder-specific Actions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - abc
          - 123
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
      
      - name: Perform actions for changes in folder
        if: ${{ contains(github.event.head_commit.modified, matrix.folder + '/') }}
        run: |
          if [[ "${{ matrix.folder }}" == "abc" ]]; then
            tree abc
          elif [[ "${{ matrix.folder }}" == "123" ]]; then
            ls 123
          fi
