name: Directory-specific Actions

on:
  push:
    branches:
      - main
    paths:
      - 'abc/**'
      - '123/**'

jobs:
  abc_changes:
    if: ${{ startsWith(github.event.head_commit.modified, 'abc/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run actions for abc folder
        # Add your actions specific to abc folder here

  folder_123_changes:
    if: ${{ startsWith(github.event.head_commit.modified, '123/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run actions for 123 folder
        # Add your actions specific to 123 folder here
