name: Folder-specific Workflows

on:
  push:
    branches:
      - main
    paths:
      - 'abc/**'
      - '123/**'

jobs:
  folder_abc:
    env:
      changes_abc: contains(github.event.head_commit.modified, 'abc/**')
    run: |
      if [ "$changes_abc" = "true" ]; then
        echo "changes done in abc folder"
      fi
    runs-on: ubuntu-latest
    name: abc Folder Workflow

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: echo "Performing actions for changes in abc folder"
  
  folder_123:
    env:
      changes_123: contains(github.event.head_commit.modified, '123/**')
    run: |
      if [ "$changes_123" = "true" ]; then
        echo "changes done in 123 folder"
      fi
    runs-on: ubuntu-latest
    name: 123 Folder Workflow

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: echo "Performing actions for changes in 123 folder"
