name: Folder Sync

on:
  push:
    branches:
      - 'abc'
      - '123'
    path:
      - 'abc/*'
      - '123/*'

jobs:
  trigger-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Add your specific actions here for abc/a1 branchh
      - name: Action for abc/ branch
        # if: github.ref == 'refs/heads/abc/**'
        run: |
          echo "Executing actions for abc/ branch"
          # Your actions for abc/a1 branch go here

      # Add your specific actions here for 123/ branch
      - name: Action for 123/ branch
        # if: github.ref == 'refs/heads/123/**'
        run: |
          echo "Executing actions for 123/ branch"
          # Your actions for 123/1.1.1 branch go here
