name: Folder-specific Workflows

on:
  push:
    branches:
      - main

jobs:
  folder_actions:
    name: Folder-specific Actions
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
      
      - name: Perform actions for changes in abc folder
        if: ${{ contains(github.event.head_commit.modified, 'abc/') }}
        run: |
          tree abc  

      - name: Perform actions for changes in 123 folder
        if: ${{ contains(github.event.head_commit.modified, '123/') }}
        run: |
          ls 123
