name: Folder-specific Workflows

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ if [ $(git diff --name-only --diff-filter=MA -- db | wc -l) -eq $(git diff --name-only --diff-filter=MA | wc -l) ]; then 'true' else 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run job if folder changed
        if: ${{ outputs.run_job == 'true' }}
        run: |
          echo "Updates made to db folder"

  folder_123:
    name: 123 Folder Workflow
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.modified, '123/**') }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
      
      - name: Perform actions for changes in 123 folder
        run: |
          ls 123  