name: actions

on:
  push:
    branches:
      - main
    paths:
      - 'abc/**'
      - '123/**'

jobs:
  abc_job:
    name: changes in abc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Example Step
        run: echo "Performing actions for changes in abc folder"


  123_job:
    name: changes in 123 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Example Step
        run: echo "Performing actions for changes in 123 folder"
