name: Directory-specific Actions

on:
  push:
    branches:
      - main

jobs:
  abc_changes:
    if: ${{ contains(github.event.head_commit.modified, 'abc/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run actions for abc folder
        run: echo "changes mane in abc folder"

  123_changes:
    if: ${{ contains(github.event.head_commit.modified, '123/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run actions for 123 folder
        run: echo "changes mane in 123 folder"
