name: Folder-specific Workflows

on:
  push:
    branches:
      - main
    paths:
      - 'abc/**'
      - '123/**'

jobs:
  folder_abc:
    runs-on: ubuntu-latest
    name: abc Folder Workflow
    env:
      changes_abc: ${{ startsWith(github.event.head_commit.modified, 'abc/**') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: echo "Performing actions for changes in abc folder"

      - name: Echo changes in abc folder
        if: ${{ env.changes_abc == 'true' }}
        run: echo "Changes detected in abc folder"

  folder_123:
    runs-on: ubuntu-latest
    name: 123 Folder Workflow
    env:
      changes_123: ${{ startsWith(github.event.head_commit.modified, '123/**') }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: echo "Performing actions for changes in 123 folder"

      - name: Echo changes in 123 folder
        if: ${{ env.changes_123 == 'true' }}
        run: echo "Changes detected in 123 folder"
