name: Folder-specific Workflows

on:
  push:
    branches:
      - main

jobs:
  folder_abc:
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Debug Modified Files
        run: echo "Performing actions for changes in abc folder"

    if: ${{contains(github.event.head_commit.modified,'abc/')&&!contains(github.event.head_commit.modified,'123/')}}
    runs-on: ubuntu-latest
    name: ABC Folder Workflow

  
  folder_123:
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: echo "Performing actions for changes in 123 folder"


    if: ${{contains(github.event.head_commit.modified,'123/')&&!contains(github.event.head_commit.modified,'abc/')}}
    runs-on: ubuntu-latest
    name: 123 Folder Workflow