name: Folder-specific Workflows

on:
  push:
    branches:
      - main
    paths:
      - 'abc/**'
      - '123/**'

jobs:
  folder_abc:
    name: ABC Folder Workflow
    runs-on: ubuntu-latest
  with:
    files: |
      abc/**
      '123/**'

    - name: Perform action when test_directory changes
      if: contains(steps.verify-changed-files.outputs.changed_files, 'abc/**')
      run: |
        echo "test_directory has changed."
    # if: contains(github.event.head_commit.modified, 'abc/')
    # steps:
    #   - name: Check out repository
    #     uses: actions/checkout@v2
      
    #   - name: Debug Modified Files
    #     run: |
    #       echo "Modified files:"
    #       echo "${{ github.event.head_commit.modified }}"
      
    #   - name: Perform actions for changes in abc folder
    #     run: |
    #       echo "changes done in abc folder"
    #       tree abc  

  folder_123:
    name: 123 Folder Workflow
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, '123/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Modified Files
        run: |
          echo "Modified files:"
          echo "${{ github.event.head_commit.modified }}"
      
      - name: Perform actions for changes in 123 folder
        run: |
          echo "changes done in 123 folder"
          ls 123  